spring.application.name=javabackend

spring.datasource.url=jdbc:postgresql://dpg-d7gsk87aqgkc739irsl0-a.oregon-postgres.render.com:5432/expense_db_zyjp
spring.datasource.username=expense_db_zyjp_user
spring.datasource.password=CVcVKt3QA1dwLSsulrsPHmK4vVy57Rpm

spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

server.port=8090


